# Multiple lines can be made a single "virtual line" because of the way that
# Travis munges each line before executing it to print out the exit status.
# It's okay for it to be on multiple physical lines, so long as you remember:
# - There can't be any leading "-"s - All newlines will be removed, so use
# ";"s

language: python
# travis can't use sudo with educational accounts because of a docker issue
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libatlas3gf-base
      - libgsl0-dev
      - libgsl0ldbl
env:
    global:
        - DEPENDS="cython numpy scipy nibabel cythongsl"

python:
    #- 3.3
    #- 3.4

matrix:
  include:
    # To test minimum dependencies
    - python: 2.7
      env:
        - COVERAGE=1
        - DEPENDS="cython==0.18  nibabel==1.3.0"
    - python: 2.7
      env:
        - DEPENDS="cython nibabel cythongsl"

notifications:
    email: false

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python --version # just to check
    - pip install $DEPENDS
    - if [ "${COVERAGE}" == "1" ]; then
      pip install coverage coveralls;
      fi
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
install:
    - python setup.py install

# command to run tests, e.g. python setup.py test
script:
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - if [ "${COVERAGE}" == "1" ]; then
      cp ../.coveragerc .;
      COVER_ARGS="--with-coverage --cover-package nlsam";
      fi
    - nosetests --with-doctest --verbose $COVER_ARGS nlsam

after_success:
    - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
