language: python
sudo: false

os:
  - linux

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libgsl0-dev
      - libgsl0ldbl

env:
    - DEPENDS="cython numpy scipy"
      DEPENDS_PIP="cythongsl dipy nibabel"
      TESTPART=test_scripts1.sh

    - DEPENDS="cython numpy scipy"
      DEPENDS_PIP="cythongsl dipy nibabel"
      TESTPART=test_scripts2.sh

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - python: 2.7
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPENDS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts1.sh
    - python: 2.7
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPENDS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts2.sh
    - python: 3.4
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPENDS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts1.sh
    - python: 3.4
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPENDS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts2.sh
    # test only on a few mac osx bots
    - os: osx
      language: generic
      before_install:
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
      env:
        - DEPENDS="cython numpy scipy"
          DEPENDS_PIP="cythongsl nibabel dipy"
          TESTPART=test_scripts1.sh
    - os: osx
      language: generic
      before_install:
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
      env:
        - DEPENDS="cython numpy scipy"
          DEPENDS_PIP="cythongsl nibabel dipy"
          TESTPART=test_scripts2.sh
    - os: osx
      language: generic
      before_install:
        - virtualenv env -p python
        - source env/bin/activate
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPENDS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts1.sh
    - os: osx
      language: generic
      before_install:
        - virtualenv env -p python
        - source env/bin/activate
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPENDS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts2.sh

notifications:
    email: false

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl; fi

    - python --version # just to check
    - pip install --upgrade pip # so that we can use wheels
    - pip install pytest coverage coveralls
    - pip install $DEPENDS --upgrade
    - pip install $DEPENDS_PIP --upgrade
    - python setup.py build_ext -i
    - python setup.py install

before_script:
    - mkdir $HOME/.python-eggs
    - chmod og-w $HOME/.python-eggs

script:
    - mkdir tester
    - cd tester
    - py.test ../nlsam/tests/ --verbose
    - echo 'Running tests $TESTPART'
    - chmod +x ../nlsam/tests/$TESTPART
    - ../nlsam/tests/$TESTPART

#after_success:
#    - coveralls
