# Multiple lines can be made a single "virtual line" because of the way that
# Travis munges each line before executing it to print out the exit status.
# It's okay for it to be on multiple physical lines, so long as you remember:
# - There can't be any leading "-"s - All newlines will be removed, so use
# ";"s

language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libgsl0-dev
      - libgsl0ldbl
      - gfortran
env:
    global:
        - DEPENDS="cython numpy scipy nibabel"
        - DEPENDS_PIP="cythongsl dipy"
        - WHEELHOST="travis-wheels.scikit-image.org"
        - WHEELHOUSE="http://${WHEELHOST}/"
python:
    #- 3.3
    #- 3.4

matrix:
  include:
    # To test minimum dependencies
    - python: 2.7
      env:
        - COVERAGE=1
        - DEPENDS="cython==0.18 numpy==1.7.1 scipy==0.12"
    - python: 2.7

notifications:
    email: false

before_install:
    #- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
 #   - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  #  - chmod +x miniconda.sh
  #  - ./miniconda.sh -b -p /home/travis/mc
  #  - export PATH=/home/travis/mc/bin:$PATH
 #   - conda update --yes conda
  #  - virtualenv --python=python venv
   # - source venv/bin/activate
    - python --version # just to check
    - virtualenv $VENV_ARGS venv
    - source venv/bin/activate
    #- pip install $DEPENDS

    #- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
install:
 #   - conda update --yes conda
    #- conda config --add channels soft-matter
  #  - conda create -n testenv --yes $DEPENDS_CONDA pip nose setuptools libgfortran python=$TRAVIS_PYTHON_VERSION
  #  - source activate testenv
    - if [ "${COVERAGE}" == "1" ]; then
      pip install coverage coveralls;
      fi
      
    - pip install --timeout=60 --no-index --trusted-host $WHEELHOST --find-links $WHEELHOUSE $DEPENDS
    - pip install $DEPENDS_PIP
    - python setup.py install

# command to run tests, e.g. python setup.py test
script:
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - if [ "${COVERAGE}" == "1" ]; then
      cp ../.coveragerc .;
      COVER_ARGS="--with-coverage --cover-package nlsam";
      fi
    - nosetests --with-doctest --verbose $COVER_ARGS nlsam

after_success:
    - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
