language: python
sudo: false

os:
  - linux

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libgsl0-dev
      - libgsl0ldbl
      - gfortran

env:
    global:
        - DEPENDS="cython numpy scipy"
        - DEPENDS_PIP="cythongsl dipy nibabel"

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - python: 2.7
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
        - DEPENDS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
    - python: 3.4
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
        - DEPENDS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
    - os: osx
      language: generic
      osx_image: xcode7.3
      before_install:
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
    - os: osx
      language: generic
      osx_image: xcode8.3
      before_install:
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
    - os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
        - DEPENDS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
      before_install:
        - virtualenv env -p python
        - source env/bin/activate
    - os: osx
      language: generic
      osx_image: xcode8.3
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
        - DEPENDS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
      before_install:
        - virtualenv env -p python
        - source env/bin/activate

notifications:
    email: false

install:
    # brew install gcc gives gfortran now
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl; fi

    - python --version # just to check
    - pip install --upgrade pip # so that we can use wheels
    - pip install nose coverage coveralls
    - pip install $DEPENDS --upgrade
    - pip install $DEPENDS_PIP --upgrade
    - python setup.py build_ext -i
    - python setup.py install

before_script:
    - mkdir $HOME/.python-eggs
    - chmod og-w $HOME/.python-eggs

script:
    - mkdir tester
    - cd tester
    - nosetests --verbose --exe --with-coverage --cover-package=nlsam ../nlsam/tests/
    - chmod +x ../nlsam/tests/test_scripts.sh
    - ../nlsam/tests/test_scripts.sh

#after_success:
#    - coveralls
