language: python
sudo: false

os:
  - linux

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libgsl0-dev
      - libgsl0ldbl
      # - gfortran

# env:
#   global:
#     - DEPS="cython numpy scipy"
#     - DEPS_PIP="cythongsl dipy nibabel"
#     - DEPS_MIN="cython==0.21 numpy==1.10.4 scipy==0.14"
#     - DEPS_PIP_MIN="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
#   matrix:
#     - DEPENDS=$DEPS
#       DEPENDS_PIP=$DEPS_PIP
#       TESTPART=test_scripts1.sh
#     - DEPENDS=$DEPS_MIN
#       DEPENDS_PIP=$DEPS_PIP_MIN
#       TESTPART=test_scripts1.sh
#     - DEPENDS=$DEPS
#       DEPENDS_PIP=$DEPS_PIP
#       TESTPART=test_scripts2.sh
#     - DEPENDS=$DEPS_MIN
#       DEPENDS_PIP=$DEPS_PIP_MIN
#       TESTPART=test_scripts2.sh

env:
    - DEPENDS="cython numpy scipy"
      DEPENDS_PIP="cythongsl dipy nibabel"
      TESTPART=test_scripts1.sh

    - DEPENDS="cython numpy scipy"
      DEPENDS_PIP="cythongsl dipy nibabel"
      TESTPART=test_scripts2.sh

    # - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
    #   DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
    #   TESTPART=test_scripts1.sh

    # - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
    #   DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
    #   TESTPART=test_scripts2.sh

  # matrix:
  #   - DEPENDS=$DEPS
  #     DEPENDS_PIP=$DEPS_PIP
  #     TESTPART=test_scripts1.sh
  #   - DEPENDS=$DEPS_MIN
  #     DEPENDS_PIP=$DEPS_PIP_MIN
  #     TESTPART=test_scripts1.sh
  #   - DEPENDS=$DEPS
  #     DEPENDS_PIP=$DEPS_PIP
  #     TESTPART=test_scripts2.sh
  #   - DEPENDS=$DEPS_MIN
  #     DEPENDS_PIP=$DEPS_PIP_MIN
  #     TESTPART=test_scripts2.sh



python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  # exclude:
  # # We can't run old numpy/scipy on newer python anyway
  #   - python: 3.5
  #     env: DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
  #   - python: 3.6
  #     env: DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.14"
  include:
    - python: 2.7
      env:
        - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts1.sh
    - python: 2.7
      env:
        - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts2.sh
    - python: 3.4
      env:
        - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts1.sh
    - python: 3.4
      env:
        - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts2.sh
    # - python: 3.4
    #   env:
    #   - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
    #     DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
    #     TESTPART=test_scripts1.sh

    #   - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
    #     DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
    #     TESTPART=test_scripts2.sh
    # test only on a few mac osx bots
    - os: osx
      language: generic
      osx_image: xcode8.3
        # - xcode7.3
        # -
          # - .3
      before_install:
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
      env:
        - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts1.sh
    - os: osx
      language: generic
      osx_image: xcode8.3
        # - xcode7.3
        # - xcode8.3
          # - .3
      before_install:
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
      env:
          - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
            DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
            TESTPART=test_scripts2.sh
    - os: osx
      language: generic
      osx_image: xcode8.3
        # - xcode7.3
        # - xcode8.3
      before_install:
        # - brew install python3
        - virtualenv env -p python
        - source env/bin/activate
      env:
        - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts1.sh
    - os: osx
      language: generic
      osx_image: xcode8.3
        # - xcode7.3
        # - xcode8.3
      before_install:
        # - brew install python3
        - virtualenv env -p python
        - source env/bin/activate
      env:
        - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
          DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
          TESTPART=test_scripts2.sh
    # - os: osx
    #   language: generic
    #   # osx_image: xcode7.3
    #   # env:
    #   #   -  DEPENDS=$DEPENDS_MIN DEPENDS_PIP=$DEPENDS_PIP_MIN
    #   before_install:
    #     - virtualenv env -p python
    #     - source env/bin/activate
    #   env:
    #     - DEPS="cython numpy scipy"
    #       DEPS_PIP="cythongsl nibabel dipy"
    #       TESTPART=test_scripts1.sh

    #     - DEPS="cython numpy scipy"
    #       DEPS_PIP="cythongsl nibabel dipy"
    #       TESTPART=test_scripts2.sh
    # - os: osx
    #   language: generic
    #   # osx_image: xcode8.3
    #   # env:
    #   #   - DEPENDS=$DEPENDS_MIN DEPENDS_PIP=$DEPENDS_PIP_MIN
    #   before_install:
    #     - virtualenv env -p python
    #     - source env/bin/activate
    #   env:
    #     - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
    #       DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
    #       TESTPART=test_scripts1.sh

    #     - DEPS="cython==0.21 numpy==1.10.4 scipy==0.14"
    #       DEPS_PIP="cythongsl==0.2.1 nibabel==2.0.1 dipy==0.11"
    #       TESTPART=test_scripts2.sh

notifications:
    email: false

install:
    # brew install gcc gives gfortran now
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl; fi

    - python --version # just to check
    - pip install --upgrade pip # so that we can use wheels
    - pip install pytest coverage coveralls
    - pip install $DEPENDS --upgrade
    - pip install $DEPENDS_PIP --upgrade
    - python setup.py build_ext -i
    - python setup.py install

before_script:
    - mkdir $HOME/.python-eggs
    - chmod og-w $HOME/.python-eggs

script:
    - mkdir tester
    - cd tester
    - py.test ../nlsam/tests/ --verbose
    - echo 'Running tests $TESTPART'
    - chmod +x ../nlsam/tests/$TESTPART
    - ../nlsam/tests/$TESTPART

#after_success:
#    - coveralls
