language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libgsl0-dev
      - libgsl0ldbl
      - gfortran
env:
    global:
        - DEPENDS="cython numpy scipy nibabel"
        - DEPENDS_PIP="cythongsl dipy"
        - WHEELHOST="travis-wheels.scikit-image.org"
        - WHEELHOUSE="http://${WHEELHOST}/"
python:

matrix:
  include:
    # To test minimum dependencies
    - python: 2.7
      env:
        - DEPENDS="cython==0.21 numpy==1.10.4 scipy==0.12 nibabel==1.3"
        - DEPENDS_PIP="cythongsl==0.2.1 dipy==0.11"
    - python: 2.7

notifications:
    email: false

before_install:
    - python --version # just to check
    - virtualenv venv
    - source venv/bin/activate

install:
    - pip install --timeout=60 --no-index --trusted-host $WHEELHOST --find-links $WHEELHOUSE $DEPENDS
    - pip install $DEPENDS_PIP nose coverage coveralls
    - python setup.py install
    - echo 'import sys; print(sys.executable)' > test.py
    - python test.py

script:
    - nosetests --verbose --exe --with-coverage --cover-package=nlsam nlsam/tests

after_success:
    - coveralls
